### PR TITLE
enhance test.c

### PR DESCRIPTION
**Pull request by vanhauser-thc**
Adds 2 changes:

1. persistent mode was not optimally used. The forkserver was installed before the main. best practice is to put it just before __AFL_LOOP

2. I added a feature for shared memory test case passing. super WIP. requires current dev of afl++

Finally: putting in the test case also https://github.com/AFLplusplus/AFL-Snapshot-LKM/ would be great. But not sure how stable it is. my test case froze when I played with it 6 weeks ago.
So WIP for sure. EDIT: doesnt freeze for me anymore and ~75% speed gain on a real target (djpeg).

If I would be an affine twitter user I would have seen the discussion prior sending my long email ;)

These benchmark tests are worst case though. The longer the time in library initialization and in main until the AFL_LOOP, the higher the speed gain.

### CODE REVIEW

**Comment by gamozolabs** [comment]
Sweet thanks, gonna try it out.

**Comment by gamozolabs** [comment]
Early results, the `__AFL_INIT` had no effect on perf. I was under the impression that `__AFL_INIT` was put at the start of main by default in AFL, thus it isn't really different manually. I could be wrong.

Testing out shmem now.

**Comment by vanhauser-thc** [comment]
in the test.c the __AFL_INIT I should just make a tiny difference.

the forkserver is installed in constructor level 5, so super early. in test.c however there is no other library, no other code in main, so its just a few stuff from libc that make the difference.

curious if the shmem really works ;) especially longer time and at scale. wrote that code when I was totally exhausted. worked for me, but only limited testing.

**Comment by gamozolabs** [comment]
Benchmarks for shared memory mode are done. Unfortunately I cannot test the kernel driver as causes the entire system to hang when an AFL process dies (perhaps only abruptly)
image

**Comment by gamozolabs** [comment]
image

**Comment by gamozolabs** [comment]
image

**Comment by gamozolabs** [comment]
From an initial glance, it appears there's about a 2x speedup on all cores when using this kernel module @ 190 cores, but I can't do a sweep because it does not exit cleanly.

**Comment by vanhauser-thc** [comment]
it worked fine for me with 2 cores - but sure finding bugs is more likely when > 100 ;)
I will create an issue as Andrea is currently busy with writing papers the next days ...

**Pull request merged**
